var dataEquipment = {
  'equips': [
    {
      'code': 'FA1-SF1-001',
      'title': 'ถังดับเพลิง 01',
      'subTitle': 'ถังดับเพลิง 01',
      'area': 'Factory 1',
      'line': 'Main Assembly Line 1',
      'status': 'NORMAL',
      'nextCheck': DateTime.parse('20230920'),
      'lastBy': 'Aukit.K',
      'lastCheck': DateTime.parse('20230820'),
    },
    {
      'code': 'FA1-SF1-002',
      'title': 'ถังดับเพลิง 02',
      'subTitle': 'ถังดับเพลิง 02',
      'area': 'Factory 1',
      'line': 'Main Assembly Line 1',
      'status': 'NORMAL',
      'nextCheck': DateTime.parse('20231005'),
      'lastBy': 'Aukit.K',
      'lastCheck': DateTime.parse('20230905'),
    },
    {
      'code': 'FA1-SF1-003',
      'title': 'ถังดับเพลิง 03',
      'subTitle': 'ถังดับเพลิง 03',
      'area': 'Factory 1',
      'line': 'Main Assembly Line 1',
      'status': 'NORMAL',
      'nextCheck': DateTime.parse('20230920'),
      'lastBy': 'Aukit.K',
      'lastCheck': DateTime.parse('20230820'),
    },
  ]
};

var dataDetail = {
  'equiplogs': [
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230820'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230720'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230620'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230520'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230420'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230320'),
    },
    {
      'code': 'FA1-SF1-001',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230220'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230820'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230720'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230620'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230520'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230420'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230320'),
    },
    {
      'code': 'FA1-SF1-002',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230220'),
    },
    {
      'code': 'FA1-SF1-003',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230820'),
    },
    {
      'code': 'FA1-SF1-003',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230720'),
    },
    {
      'code': 'FA1-SF1-003',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230620'),
    },
    {
      'code': 'FA1-SF1-003',
      'status': 'NORMAL',
      'remark': '',
      'checkBy': 'Aukit.K',
      'checkDT': DateTime.parse('20230520'),
    },
  ]
};
